version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-chat-ebook
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: chat-ebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duchuy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat-ebook-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-chat-ebook
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data
    networks:
      - chat-ebook-network
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_web_stomp &&
             rabbitmq-plugins enable --offline rabbitmq_stomp &&
             rabbitmq-server"

  redis:
    image: redis:latest
    container_name: redis-chat-ebook
    hostname: redis
    ports:
      - "6380:6379"
    networks:
      - chat-ebook-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-chat-ebook
    links:
      - postgres
      - rabbitmq
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chat-ebook
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: duchuy
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - tempo
      - loki
      - prometheus
    networks:
      - chat-ebook-network

  nginx:
    image: nginx:latest
    container_name: nginx-chat-ebook
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-ebook-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./observation/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - chat-ebook-network

  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observation/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./observation/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "9411:9411"
    networks:
      - chat-ebook-network

  loki:
    image: grafana/loki:main
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    networks:
      - chat-ebook-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./observation/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./observation/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - chat-ebook-network

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  chat-ebook-network:
    driver: bridge
    name: chat-ebook-network