server:
  port: 8081
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-ebook
    username: postgres
    password: duchuy
    hikari:
      max-lifetime: 60000
      auto-commit: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
  thymeleaf:
    mode: HTML
  liquibase:
    enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
springdoc:
  swagger-ui:
    path: /api/index.html