-- liquibase formatted sql

-- changeset duchuy:1744173272482-4
ALTER TABLE messages
    ADD sender_type VARCHAR(255);

-- changeset duchuy:1744173272482-1
ALTER TABLE messages
    DROP COLUMN id;

-- changeset duchuy:1744173272482-2
ALTER TABLE messages
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;


